<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?> - <?= date('Y-m-d') ?></title>
    <style>
        @page { margin: 20px; }
        body { font-family: Arial, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 10px; }
        .library-name { font-size: 20px; font-weight: bold; }
        .report-title { font-size: 16px; margin: 10px 0; }
        .print-date { font-size: 11px; margin-bottom: 15px; }
        .summary { margin: 15px 0; padding: 10px; background: #f5f5f5; border-radius: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #f0f0f0; text-align: left; padding: 8px; border: 1px solid #ddd; font-weight: bold; }
        td { padding: 8px; border: 1px solid #ddd; vertical-align: top; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 10px; text-align: center; }
        .no-data { text-align: center; padding: 20px; font-style: italic; color: #666; }
        .book-cover { width: 40px; height: 60px; object-fit: cover; border: 1px solid #ddd; }
        .qty-low { color: #dc3545; font-weight: bold; }
        .qty-medium { color: #ffc107; }
        .qty-high { color: #28a745; }
    </style>
</head>
<body>
    <div class="header">
        <div class="library-name"><?= $library_name ?></div>
        <div class="report-title"><?= $title ?></div>
        <div class="print-date">Printed on: <?= $print_date ?></div>
    </div>
    
    <div class="summary">
        Total Available Books: <strong><?= count($results) ?></strong> |
        Total Copies in Stock: <strong><?= array_sum(array_column($results, 'quantity')) ?></strong>
    </div>
    
    <?php if(empty($results)): ?>
        <div class="no-data">No available books found in inventory.</div>
    <?php else: ?>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Cover</th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Publisher</th>
                    <th>Year</th>
                    <th>Category</th>
                    <th>ISBN</th>
                    <th>Quantity</th>
                    <th>Shelf Location</th>
                </tr>
            </thead>
            <tbody>
                <?php $counter = 1; ?>
                <?php foreach($results as $row): ?>
                <tr>
                    <td class="text-center"><?= $counter++ ?></td>
                    <td class="text-center">
                        <?php if(!empty($row['image'])): ?>
                            <img src="<?= base_url('uploads/books/' . $row['image']) ?>" 
                                 alt="Cover" 
                                 class="book-cover">
                        <?php else: ?>
                            <div style="width: 40px; height: 60px; border: 1px solid #ddd; display: flex; align-items: center; justify-content: center;">
                                <span style="font-size: 10px;">No Image</span>
                            </div>
                        <?php endif; ?>
                    </td>
                    <td><?= esc($row['title']) ?></td>
                    <td><?= esc($row['author']) ?></td>
                    <td><?= esc($row['publisher']) ?></td>
                    <td><?= esc($row['year']) ?></td>
                    <td><?= esc($row['category']) ?></td>
                    <td><?= esc($row['isbn']) ?></td>
                    <td class="text-center">
                        <span class="<?= $row['quantity'] > 5 ? 'qty-high' : ($row['quantity'] > 0 ? 'qty-medium' : 'qty-low') ?>">
                            <?= $row['quantity'] ?>
                        </span>
                    </td>
                    <td><?= esc($row['shelf_location']) ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
    
    <div class="footer">
        <p>Report generated by Digital Library System | Page 1 of 1</p>
    </div>
    
<script>
// Auto print when page loads
window.onload = function() {
    // Give it a small delay to ensure content is loaded
    setTimeout(function() {
        window.print();
        
        // Check if print was cancelled or completed
        window.onafterprint = function() {
            // Close window after printing (or if print was cancelled)
            setTimeout(function() {
                window.close();
            }, 100);
        };
        
        // Fallback: close after 5 seconds if onafterprint doesn't fire
        setTimeout(function() {
            if (!window.closed) {
                window.close();
            }
        }, 5000);
        
    }, 500); // 0.5 second delay to ensure everything loads
};

// Handle browser back button or manual close
window.onbeforeunload = function() {
    return null; // No warning message when closing
};

// Alternative approach for browsers that don't support onafterprint well
let beforePrint = function() {
    console.log('Print started...');
};

let afterPrint = function() {
    console.log('Print completed...');
    setTimeout(function() {
        window.close();
    }, 100);
};

// Webkit browsers
if (window.matchMedia) {
    let mediaQueryList = window.matchMedia('print');
    mediaQueryList.addListener(function(mql) {
        if (mql.matches) {
            beforePrint();
        } else {
            afterPrint();
        }
    });
}

// Add a manual close button for users
document.addEventListener('DOMContentLoaded', function() {
    // Create close button
    const closeBtn = document.createElement('button');
    closeBtn.innerHTML = '✕ Close Window';
    closeBtn.style.cssText = `
        position: fixed;
        top: 10px;
        right: 10px;
        background: #dc3545;
        color: white;
        border: none;
        padding: 8px 15px;
        border-radius: 4px;
        cursor: pointer;
        font-size: 12px;
        z-index: 10000;
        display: none; /* Hide by default, show only if needed */
    `;
    closeBtn.onclick = function() {
        window.close();
    };
    document.body.appendChild(closeBtn);
    
    // Show close button after 3 seconds if still open
    setTimeout(function() {
        if (!window.closed) {
            closeBtn.style.display = 'block';
        }
    }, 3000);
});
</script>
</body>
</html>