<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library Members List - Print</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
        }
        .header .date {
            font-size: 11px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th {
            background-color: #f2f2f2;
            text-align: left;
            padding: 8px;
            border: 1px solid #ddd;
            font-weight: bold;
        }
        td {
            padding: 8px;
            border: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        @media print {
            .no-print {
                display: none;
            }
            body {
                margin: 0;
                padding: 0;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Library Members List</h1>
        <div class="date">Printed on: <?= date('F j, Y h:i A') ?></div>
        <div class="date">Total Members: <?= count($members) ?></div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Full Name</th>
                <th>Address</th>
                <th>Contact Number</th>
                <th>User ID</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <?php if(empty($members)): ?>
                <tr>
                    <td colspan="6" style="text-align: center; padding: 20px;">No members registered yet.</td>
                </tr>
            <?php else: ?>
                <?php $counter = 1; ?>
                <?php foreach($members as $member): ?>
                <tr>
                    <td><?= $counter++ ?></td>
                    <td><?= esc($member['full_name']) ?></td>
                    <td><?= esc($member['address']) ?></td>
                    <td><?= esc($member['contact_number']) ?></td>
                    <td>#<?= $member['user_id'] ?></td>
                    <td>Active</td>
                </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Library Management System | <?= date('Y') ?></p>
        <button class="no-print" onclick="window.print()" style="padding: 8px 16px; background: #007bff; color: white; border: none; cursor: pointer;">
            Print This Page
        </button>
        <button class="no-print" onclick="window.close()" style="padding: 8px 16px; background: #6c757d; color: white; border: none; cursor: pointer; margin-left: 10px;">
            Close Window
        </button>
    </div>

<script>
    // Auto-print when page loads
    window.onload = function() {
        window.print();
    };
</script>
</body>
</html>